# Generated by Django 2.0.9 on 2018-12-09 07:34

from django.db import migrations
from django.contrib.auth.models import Group


def create_default_groups(apps, schema_editor):
    volunteer_group = Group("Volunteer")
    fr_group = Group("First Responder")
    chief_group = Group("Chief")

    volunteer_group.save()
    fr_group.save()
    chief_group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
