# Generated by Django 2.0.9 on 2018-12-09 07:34

from django.db import migrations
from django.contrib.auth.models import Group


def create_default_groups(apps, schema_editor):
    volunteer_group = Group.objects.create(name="Volunteer")
    fr_group = Group.objects.create(name="First Responder")
    chief_group = Group.objects.create(name="Chief")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
