# Generated by Django 2.1.4 on 2018-12-09 19:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
