# Generated by Django 2.1.4 on 2018-12-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticket_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('S', 'Finished'), ('F', 'Failure')], max_length=2)),
                ('related_tickets', models.ManyToManyField(to='core.Ticket')),
            ],
        ),
    ]
