# Generated by Django 2.1.4 on 2018-12-10 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='used_in_mission',
            new_name='allocated_to',
        ),
        migrations.AddField(
            model_name='mission',
            name='first_responders',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
