# Generated by Django 2.1.4 on 2018-12-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181210_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='allocated_to',
        ),
        migrations.AddField(
            model_name='mission',
            name='resources',
            field=models.ManyToManyField(to='core.Resource'),
        ),
    ]
