# Generated by Django 2.1.4 on 2018-12-11 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181211_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='first_responders',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mission',
            name='resources',
            field=models.ManyToManyField(blank=True, to='core.Resource'),
        ),
    ]
